### PR TITLE
add APIkey auth capability using headers

### PR DESCRIPTION
**Pull request by BarthV**
#10

Thanks to review this little addition :angel:

### CODE REVIEW

**Comment by BarthV** [comment]
:up: :)

**Comment by hartfordfive** [comment]
@BarthV Thank you for the PR.  I apologize for the delay although we're just in the process of establishing our Contributor License Agreement so it might take just a bit longer.  Once it's ready, i'll notify you so that you can sign the CLA before I accept/merge your PR.

**Comment by whz** [comment]
🆙

**Comment by gustavosoares** [comment]
up!

**Comment by nicolasbrechet** [comment]
🆙

**Pull request merged**
